services:
  db:
    container_name: db
    image: postgres:17
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend
  api:
    build:
      context: .
      target: development
    environment:
      - BUN_WATCH_MODE=1
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      sh -c "
        echo 'Initializing database...' &&
        sh ./init-db.sh &&
        echo 'Starting development server...' &&
        bun dev
      "
    volumes:
      - .:/app
      - /app/node_modules
      - /bun-cache:/bun-dir
      - ./init-db.sh:/app/init-db.sh
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/healthcheck']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  drizzle-studio:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - SALT_WORK_FACTOR=${SALT_WORK_FACTOR}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
    command: >
      sh -c "
        echo 'Starting Drizzle Studio...' &&
        bun run db:studio
      "
    ports:
      - '4983:4983'
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
    driver: local
  bun-cache:
    driver: local
