services:
  db:
    container_name: db
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
  api:
    build:
      context: .
      target: development
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "deno task migrate && deno task dev"
    volumes:
      - .:/app
      - /deno-cache:/deno-dir
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
    driver: local
  deno-cache:
    driver: local
    
